import React from "react";

const aboutData = [
  {
    src: "/images/web/search.png",
    alt: "search_slogan_png",
    heading: "Search",
    text: "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
  },
  {
    src: "/images/web/select.png",
    alt: "select_slogan_png",
    heading: "Select",
    text: "Choose from thousands of options generated by the slogan maker that fit your needs.",
  },
  {
    src: "/images/web/standout.png",
    alt: "standout_slogan_png",
    heading: "Stand out",
    text: "Congrats on your new slogan. It's time to win the world!",
  },
];

export const About = () => {
  return (
    <div className="flex-row about-container">
      {aboutData.map((item) => (
        <div className='flex-column about-div'>
          <img src={item.src} alt={item.alt} className='about-img' />
          <h5 className='pr'>{item.heading}</h5>
          <p className='gray-text'>{item.text}</p>
        </div>
      ))}
    </div>
  );
};
